export const paths = {
  overview: "/",
  guides: {
    installation: "/guides/installation",
    behavior: "/guides/behavior",
    theming: "/guides/theming",
    accessibility: "/guides/accessibility",
    registry: "/guides/registry",
    react: "/guides/react",
  },
  foundations: {
    color: "/foundations/color",
    typography: "/foundations/typography",
    geometry: "/foundations/geometry",
    motion: "/foundations/motion",
  },
  components: {
    actions: {
      button: "/components/actions/button",
      toggles: "/components/actions/toggles",
      commandBar: "/components/actions/command-bar",
      bulkActionToolbar: "/components/actions/bulk-action-toolbar",
    },
    forms: {
      textFields: "/components/forms/text-fields",
      selection: "/components/forms/selection-controls",
      numberInput: "/components/forms/number-input",
      passwordInput: "/components/forms/password-input",
      searchBox: "/components/forms/search-box",
      multiSelect: "/components/forms/multi-select",
      combobox: "/components/forms/combobox",
      searchableSelect: "/components/forms/searchable-select",
      inputOtp: "/components/forms/input-otp",
      dateTime: "/components/forms/range-date-time",
      calendar: "/components/forms/calendar",
      datePicker: "/components/forms/date-picker",
      fileUpload: "/components/forms/file-upload",
    },
    primitives: {
      staticPrimitives: "/components/primitives/static-primitives",
      aspectRatio: "/components/primitives/aspect-ratio",
      containerColumns: "/components/primitives/container-responsive-columns",
      styledLinks: "/components/primitives/styled-links",
      blockquote: "/components/primitives/blockquote",
      codeBlock: "/components/primitives/code-block",
      iconCatalog: "/components/primitives/icons",
      visuallyHidden: "/components/primitives/visually-hidden",
      direction: "/components/primitives/direction",
      tags: "/components/primitives/tags-chips",
    },
    navigation: {
      topBar: "/components/navigation/top-bar",
      menubar: "/components/navigation/menubar",
      navigationMenu: "/components/navigation/navigation-menu",
      breadcrumbs: "/components/navigation/breadcrumbs",
      pagination: "/components/navigation/pagination",
      accordion: "/components/navigation/accordion",
      tabs: "/components/navigation/tabs",
      carousel: "/components/navigation/carousel",
    },
    overlays: {
      tooltip: "/components/overlays/tooltip",
      dropdownMenu: "/components/overlays/dropdown-menu",
      contextMenu: "/components/overlays/context-menu",
      dialog: "/components/overlays/dialog",
      alertDialog: "/components/overlays/alert-dialog",
      drawer: "/components/overlays/drawer",
      commandPalette: "/components/overlays/command-palette",
      hoverCard: "/components/overlays/hover-card",
    },
    feedback: {
      badges: "/components/feedback/badges",
      alerts: "/components/feedback/alerts",
      progress: "/components/feedback/progress",
      stepper: "/components/feedback/stepper",
      loading: "/components/feedback/loading",
      statusIndicator: "/components/feedback/status-indicator",
      toast: "/components/feedback/toast",
      notificationCenter: "/components/feedback/notification-centre",
      emptyState: "/components/feedback/empty-state",
      errorState: "/components/feedback/error-state",
    },
    dataDisplay: {
      records: "/components/data-display/metrics-records-activity",
      activityFeed: "/components/data-display/activity-feed",
      filterBar: "/components/data-display/filter-bar",
      dataTable: "/components/data-display/advanced-data-table",
      treeView: "/components/data-display/tree-view",
    },
    visualization: {
      lineChart: "/components/visualization/line-chart",
      sparklines: "/components/visualization/sparklines",
      barChart: "/components/visualization/bar-chart",
      accessibleSummary: "/components/visualization/accessible-summary",
    },
    media: {
      imageLightbox: "/components/media/image-lightbox",
      mediaCarousel: "/components/media/media-carousel",
      uploadDropzone: "/components/media/upload-dropzone",
      batchProgressMonitor: "/components/media/batch-progress-monitor",
      gallery: "/components/media/gallery",
      rating: "/components/media/rating",
      protectedMedia: "/components/media/protected-media",
      batchPlan: "/components/media/batch-plan",
    },
    ai: {
      chatThread: "/components/ai/chat-thread",
      promptComposer: "/components/ai/prompt-composer",
      messageScroller: "/components/ai/message-scroller",
      attachmentPreviews: "/components/ai/attachment-previews",
      generationQueue: "/components/ai/generation-queue",
      modelSelector: "/components/ai/model-selector",
      parameterInspector: "/components/ai/parameter-inspector",
      beforeAfter: "/components/ai/before-after-comparison",
    },
    layouts: {
      applicationShell: "/components/layouts/application-shell",
      sidebar: "/components/layouts/sidebar",
      authentication: "/components/layouts/authentication",
      registration: "/components/layouts/registration",
      welcomeBack: "/components/layouts/welcome-back",
      splitWorkspace: "/components/layouts/split-workspace",
      scrollArea: "/components/layouts/scroll-area",
      resizablePanels: "/components/layouts/resizable-panels",
    },
  },
} as const;

function collectPaths(value: unknown): string[] {
  if (typeof value === "string") return [value];
  if (!value || typeof value !== "object") return [];
  return Object.values(value).flatMap(collectPaths);
}

export const routePaths = collectPaths(paths);

export const legacyHashRedirects: Record<string, string> = {
  overview: paths.overview,
  color: paths.foundations.color,
  typography: paths.foundations.typography,
  geometry: paths.foundations.geometry,
  motion: paths.foundations.motion,
  actions: paths.components.actions.button,
  forms: paths.components.forms.textFields,
  primitives: paths.components.primitives.staticPrimitives,
  navigation: paths.components.navigation.topBar,
  overlays: paths.components.overlays.tooltip,
  feedback: paths.components.feedback.badges,
  data: paths.components.dataDisplay.records,
  charts: paths.components.visualization.lineChart,
  media: paths.components.media.gallery,
  layouts: paths.components.layouts.applicationShell,
};
