import { icon } from "../icons.js";
import { card, section } from "./shared.js";

export const formsSection = section(
  "forms",
  "07",
  "Forms",
  "Native controls remain the baseline. Every label is associated, focus is visible, validation is explicit, and control sizing follows the original Nyx 11 / 13 / 15 hierarchy.",
  `<div class="docs-grid">
    ${card("Text fields", `<div class="docs-form-grid"><label class="nyx-field" for="project-name"><span class="nyx-label">Project name</span><input class="nyx-input" id="project-name" value="night-operations" /></label><label class="nyx-field" for="record-search"><span class="nyx-label">Search</span><div class="nyx-input-group"><input class="nyx-input" id="record-search" placeholder="Filter records"/><button class="nyx-button nyx-icon-button" type="button" aria-label="Search">${icon("search")}</button></div></label><label class="nyx-field docs-form-span" for="project-description"><span class="nyx-label">Description</span><textarea class="nyx-textarea" id="project-description">Reusable operational interface components.</textarea><span class="nyx-field-hint">Maximum 240 characters.</span></label><label class="nyx-field" for="invalid-value"><span class="nyx-label">Invalid value</span><input class="nyx-input" id="invalid-value" aria-invalid="true" aria-describedby="validation-error" value="bad/value"/><span class="nyx-field-error" id="validation-error">Use letters, numbers, and hyphens.</span></label><label class="nyx-field" for="disabled-value"><span class="nyx-label">Disabled</span><input class="nyx-input" id="disabled-value" disabled value="Unavailable"/></label></div>`, "Semantic")}
    ${card("Selection", `<div class="docs-form-grid"><label class="nyx-field" for="region"><span class="nyx-label">Region</span><select class="nyx-select" id="region"><option>Tokyo</option><option>London</option><option>New York</option></select></label><label class="nyx-field" for="quantity"><span class="nyx-label">Quantity</span><input class="nyx-input" id="quantity" type="number" value="24" min="1"/></label><label class="nyx-choice" for="notices"><input id="notices" type="checkbox" checked/>Receive operational notices</label><div class="docs-column" role="radiogroup" aria-label="Environment"><label class="nyx-choice" for="env-production"><input id="env-production" type="radio" name="env" checked/>Production</label><label class="nyx-choice" for="env-staging"><input id="env-staging" type="radio" name="env"/>Staging</label></div><label class="nyx-switch" for="automatic-deployment"><input id="automatic-deployment" type="checkbox" checked/><span class="nyx-switch-track"></span><span>Automatic deployment</span></label><div class="nyx-segmented"><input id="seg-a" name="segment" type="radio" checked/><label for="seg-a">Grid</label><input id="seg-b" name="segment" type="radio"/><label for="seg-b">List</label></div></div>`, "Keyboard ready")}
    ${card("Range, date and time", `<div class="docs-form-grid"><label class="nyx-field docs-form-span" for="strength"><span class="nyx-label">Strength · <output data-range-output for="strength">68</output></span><input class="nyx-range" id="strength" data-range-input type="range" min="0" max="100" value="68"/></label><label class="nyx-field" for="start-date"><span class="nyx-label">Date</span><input class="nyx-input" id="start-date" type="date" value="2026-09-17"/></label><label class="nyx-field" for="start-time"><span class="nyx-label">Time</span><input class="nyx-input" id="start-time" type="time" value="17:30"/></label></div>`, "Native")}
    ${card("File upload", `<label class="nyx-file" for="asset-upload">${icon("upload")}<strong>Choose files or drop them here</strong><span class="nyx-field-hint">PNG, JPG, WEBP · 20 MB maximum</span><input class="sr-only" id="asset-upload" type="file" multiple/></label>`, "Drop zone")}
  </div>`,
  "forms input textarea select checkbox radio switch range number search date time validation file upload segmented",
);
